services:
  odoo:
    image: odoo:18.0
    container_name: odoo_app
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo
      - ./backend/custom_addons:/mnt/extra-addons
      - ./backend/odoo.conf:/etc/odoo/odoo.conf:ro
    command: ["--config=/etc/odoo/odoo.conf"]

  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=01092016
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80" # Redirect sang HTTPS
      - "443:443" # HTTPS cho cả frontend + backend
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      # - ./react_build:/usr/share/nginx/html:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - odoo
    restart: always

volumes:
  odoo-data:
  db-data:
