[options]
admin_passwd = superadmin123
db_host = db
db_port = 5432
db_user = odoo
db_password = 01092016
db_name = kdpd_db
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
proxy_mode = True
http_enable = True
xmlrpc_port = 8069
server_wide_modules = web,project,my_custom_api,custom_auth
dev_mode = True