# D:/.../HRMS/nginx/default.conf

# Khai báo các upstream server để Nginx có thể tìm thấy Odoo
upstream odoo_backend {
    server odoo:8069;
}
upstream odoo_longpolling {
    server odoo:8072;
}

server {
    listen 80;
    server_name localhost;

    # Tăng giới hạn dung lượng file upload
    client_max_body_size 200M;

    # Tăng thời gian chờ
    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    # === 1. PROXY CHO LONGPOLLING ===
    location /longpolling/ {
        proxy_pass http://odoo_longpolling;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # === 2. PROXY CHO TẤT CẢ CÁC YÊU CẦU API VÀ ODOO BACKEND ===
    location / {
        proxy_pass http://odoo_backend;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
    }
}