# nginx/nginx.conf

map $http_origin $cors_header {
    ~^http://localhost(:3000)?$ $http_origin;
}

server {
    listen 80;
    server_name localhost;

    client_max_body_size 128M;

    # Tự động thêm dấu / sau /odoo
    location = /odoo {
        return 301 /odoo/;
    }

    # Backend Odoo UI
    location /odoo/ {
        proxy_pass http://odoo:8069;   # KHÔNG có dấu / ở cuối
        proxy_redirect off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Static files (JS, CSS, images) của Odoo
    location /odoo/web/static/ {
        proxy_cache_valid 200 90m;
        proxy_buffering on;
        expires 90d;
        proxy_pass http://odoo:8069/web/static/;
    }

    # API & longpolling
    location ~ ^/(web|jsonrpc|api|base_setup|mail|report|longpolling)(/.*)?$ {
        add_header 'Access-Control-Allow-Origin' $cors_header always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' '*' always;

        if ($request_method = 'OPTIONS') {
            return 204;
        }

        # longpolling (bus)
        if ($uri ~* "^/longpolling") {
            proxy_pass http://odoo:8072;
        }
        # Các request khác
        if ($uri !~* "^/longpolling") {
            proxy_pass http://odoo:8069;
        }

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
